### ISSUE TITLE
Error When Running

### ISSUE THREAD

**Issue by hanaafiqp** [Davies-K/Taskez#2]
Hi, thanks for your work. 
I just want to ask, why i get error like this ? What should i do ? 

> An Observatory debugger and profiler on Android SDK built for x86 is available at:
> http://127.0.0.1:61694/sEw9W_TnKUc=/
> The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at:
> http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A61694%2FsEw9W_TnKUc%3D%2F
> W/.example.taske(12401): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
> W/.example.taske(12401): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
> W/.example.taske(12401): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
> W/.example.taske(12401): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
> W/.example.taske(12401): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
> 
> ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════ 
> The following assertion was thrown during layout:
> A RenderFlex overflowed by 40 pixels on the right.
> 
> The relevant error-causing widget was:
>   Row
>   file:///C:/Users/Administrator.SPCWIT011/Downloads/Taskez-main/lib/Screens/Onboarding/onboarding_ca  rousel.dart:122:23
> 
> To inspect this widget in Flutter DevTools, visit:
> http://127.0.0.1:9101/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A61694%2FsEw9W_TnKUc%3D%2F&inspectorRef=inspector-0
> 
> The overflowing RenderFlex has an orientation of Axis.horizontal.
> The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and    
> black striped pattern. This is usually caused by the contents being too big for the RenderFlex.      
> Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
> RenderFlex to fit within the available space instead of being sized to their natural size.
> This is considered an error condition because it indicates that there is content that cannot be      
> seen. If the content is legitimately bigger than the available space, consider clipping it with a    
> ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,   
> like a ListView.
> The specific RenderFlex in question is: RenderFlex#c8e66 relayoutBoundary=up6 OVERFLOWING:
>   needs compositing
>   creator: Row ← Column ← Padding ← Column ← Stack ← Container ←
>   AnnotatedRegion<SystemUiOverlayStyle>
>     ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ←
>     AnimatedBuilder ← ⋯
>   parentData: offset=Offset(0.0, 128.0); flex=null; fit=null (can use size)
>   constraints: BoxConstraints(0.0<=w<=320.0, 0.0<=h<=Infinity)
>   size: Size(320.0, 60.0)
>   direction: horizontal
>   mainAxisAlignment: spaceBetween
>   mainAxisSize: max
>   crossAxisAlignment: center
>   textDirection: ltr
>   verticalDirection: down
> ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤ 
> ════════════════════════════════════════════════════════════════════════════════════════════════════ 
> 
> Another exception was thrown: A RenderFlex overflowed by 343 pixels on the bottom.
> 
> Another exception was thrown: A RenderFlex overflowed by 46 pixels on the right.
> 
> Another exception was thrown: A RenderFlex overflowed by 246 pixels on the bottom.
> 
> Another exception was thrown: Incorrect use of ParentDataWidget.
> 
> Another exception was thrown: A RenderFlex overflowed by 22 pixels on the right.
> 
> Another exception was thrown: A RenderFlex overflowed by 25 pixels on the right.
> 
> Another exception was thrown: A RenderFlex overflowed by 9.0 pixels on the right.
> 
> Another exception was thrown: A RenderFlex overflowed by 305 pixels on the bottom.
> 
> Another exception was thrown: A RenderFlex overflowed by 22 pixels on the right.
> 
> Another exception was thrown: A RenderFlex overflowed by 25 pixels on the right.
> 
> Another exception was thrown: A RenderFlex overflowed by 9.0 pixels on the right.
> 
> Another exception was thrown: A RenderFlex overflowed by 22 pixels on the right.
> 
> Another exception was thrown: A RenderFlex overflowed by 25 pixels on the right.
> 
> Another exception was thrown: A RenderFlex overflowed by 9.0 pixels on the right.

**Comment by Davies-K** [comment]
Hello friend,
You are welcome. Kindly give the project a star or you can contribute to it
in anyway you want. Please can I know the android version you are running?
And the final question I have is was the project able to run or not at all?

**Comment by Davies-K** [comment]
Hello, I have fixed the overflow issue as well. You should have any now
