### ISSUE TITLE
Overflow issues.

### ISSUE THREAD

**Issue by tangible-idea** [Davies-K/Taskez#4]
I took a look of your commit hash: c8deb3d
but still have some issue with Pixel 4 device which has 1080 x 2280 pixels, 19:9 ratio.
What about chainging the height factor  * 1.4 to 1.3 ?
P.S: many thanks to your project. I have learned many via this project.
![image](https://user-images.githubusercontent.com/4496005/128042846-ca04c2ea-a8ae-4b91-9644-299b1d0f80c2.png)

**Comment by Davies-K** [comment]
Hello Mark, thanks for your contribution. Have you updated recently? If so
we can consider changing the height factor. Again for the profile page we
missed one page before the page you committed. Attached is the image of the
screen we missed.

**Comment by Davies-K** [comment]
![1B818692-61E1-4143-BF27-B731527C1D5F_1_201_a](https://user-images.githubusercontent.com/32754191/128044876-4dfdfede-416a-4c4a-a37e-f8e1cb9c5162.jpeg)

**Comment by tangible-idea** [comment]
Yes, Feel free to advice to my contribution too :)
Also I saw the screen you attached. I was wondering what is this screen about. I assumed it as the page that you click the other person's page. 
and the page I have commited is about 'my' profile page. 
am I get it right?

**Comment by Davies-K** [comment]
Hi Mark, the screen I attached is the "My Profile" screen. When you take a look at the pages in the readme section, you will realize that that page( page I attached earlier) has a log out button extended at the bottom of the screen, clearly indicating that, it is the current user profile.

**Comment by tangible-idea** [comment]
@Davies-K Gotcha!
